services:
  jds.fetch.app:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    container_name: jds.fetch.app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - jds.redis

  jds.redis:
    image: redis:latest
    container_name: jds.redis
    command:
      ["redis-server", "--requirepass", "${REDIS_PASSWORD:-redis@secret}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
